package minerful.automaton.concept;

import java.util.HashMap;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;

import org.apache.log4j.BasicConfigurator;

import dk.brics.automaton.Automaton;
import dk.brics.automaton.State;
import dk.brics.automaton.Transition;
import minerful.automaton.AutomatonFactory;
import minerful.automaton.utils.AutomatonUtils;
import minerful.concept.TaskChar;
import minerful.concept.constraint.Constraint;
import minerful.concept.constraint.existence.AtMost2;
import minerful.concept.constraint.relation.CoExistence;
import minerful.concept.constraint.relation.Succession;
import minerful.utils.MessagePrinter;

/**
 * Interesting class wrapping an automaton and decorates the latter's state with 
 * (1) the characters that led there excluding loops and cycles, and
 * (2) an indication whether the accepting state is a permanent acceptance.
 */
public class AnnotatedAutomaton {
	public static MessagePrinter logger = MessagePrinter.getInstance(AnnotatedAutomaton.class);

	public final Automaton automaton;
	/**
	 * State decorations label the automaton states with the characters that led there excluding loops and cycles.
	 */
	private Map<State, Set<Character>> stateDecorations;
	/**
	 * Permanently satisfying states are accepting states such that every alphabet's symbol (1) is enabled and (2) leads to a loop.
	 */
	private final Set<State> permanentlySatisfyingStates;
	/**
	 * The set of symbols with which the automaton can label its transitions
	 */
	public final Character[] declaredAlphabet;

	public AnnotatedAutomaton(Automaton automaton, Character[] alphabet) {
		this.automaton = automaton;
		this.stateDecorations = new HashMap<State, Set<Character>>(automaton.getNumberOfStates(), 1);
		this.permanentlySatisfyingStates = new TreeSet<State>();
		this.declaredAlphabet = alphabet;
		annotateAutomatonStatesWithRelevantTransitionHistory();
	}
	
	public void annotateAutomatonStatesWithRelevantTransitionHistory() {
		State initialState = this.automaton.getInitialState();
		// Kick off the recursion!
		annotateStateWithRelevantTransitionHistory(initialState, new TreeSet<State>(), new TreeSet<Character>());
	}
	
	/**
	 * This is a depth-first search. It decorates states with the alphabet of the acyclic words leading to it.
	 * By acyclic words we mean strings generated by traversing the automaton excluding loops and cycles.
	 * @param state A state in the automaton
	 * @param visitedStates The list of visited states during this execution
	 * @param memorableCharsSoFar The relevant characters leading to the current state
	 */
	public void annotateStateWithRelevantTransitionHistory(State state, Set<State> visitedStates, Set<Character> memorableCharsSoFar) {
		logger.debug(String.format("Adding state %d to the visited states", state.hashCode()));
		visitedStates.add(state);
		State necState = null;
		// Remains true if from this state we can only loop
		boolean onlyLooping = true;
		// Records how many actions are traversed. To be used later to test whether their number equates the cardinality of the alphabet.
		int numOfActionsCovered = 0;
		for (Transition trans: state.getTransitions()) {
			necState = trans.getDest();
			if (necState == state) { // Looping?
				logger.debug(String.format("Characters %c-%c from state %d lead to a loop", trans.getMin(), trans.getMax(), state.hashCode()));
			}
			else {
				onlyLooping = false;
				if (visitedStates.contains(necState)) { // Cycling?
					logger.debug(String.format("Characters %c-%c from state %d lead to a cycle", trans.getMin(), trans.getMax(), state.hashCode())); 
				}
				else {
					logger.debug(String.format("Traversing trans. %c-%c from state %d to state %d", trans.getMin(), trans.getMax(), state.hashCode(), necState.hashCode())); 
					if (!stateDecorations.containsKey(necState)) {
						stateDecorations.put(necState, new TreeSet<Character>(memorableCharsSoFar));
					}
					Set<Character> memorableChars = stateDecorations.get(necState);
					for (char chr = trans.getMin(); chr <= trans.getMax(); chr++) {
						memorableChars.add(chr);
					}
					logger.debug(String.format("Memorable chars of next state %d: %s", necState.hashCode(), memorableChars)); 
					// Recursion!
					annotateStateWithRelevantTransitionHistory(necState, visitedStates, memorableChars);
				}
			}
			numOfActionsCovered += (trans.getMax() - trans.getMin() + 1); // +1 because extremes are included
		}
		// Remember, among the accepting states from which every action is enabled...
		if (state.isAccept()) {
			// ... the permanently satisfying states
			if (onlyLooping && numOfActionsCovered == declaredAlphabet.length) {
				logger.debug(String.format("State %d is permanently satisfying", state.hashCode()));
				permanentlySatisfyingStates.add(state);
			}
		}
		// Once the DFS from the current state is finished, we can remove this state from the visited ones.
		// We need this to be able to annotate states reached from concurrent branches without cycles.
		visitedStates.remove(state);
		return;
	}
	
	public Set<Character> getStateAnnotation(State state) {
		return stateDecorations.get(state);
	}
	
	public boolean isPermanentlySatisfying(State state) {
		return permanentlySatisfyingStates.contains(state);
	}
	
	public static void main(String[] args) {
		BasicConfigurator.configure();
		Constraint[] cnss = {
				new Succession(new TaskChar('A'), new TaskChar('B')),
				new CoExistence(new TaskChar('A'), new TaskChar('B')),
				new AtMost2(new TaskChar('A')),
		};
		Automaton aut = null;
		for (Constraint cns : cnss) {
			logger.printlnOut("Constraint %s", cns);
			cns = cns.getSymbolic();
			aut = AutomatonFactory.buildAutomatonWithWildcard(cns);
			Character[] alphabet = AutomatonUtils.createAlphabetArray(cns.getInvolvedTaskCharIdentifiers(), true);
			new AnnotatedAutomaton(aut, alphabet);
		}
	}

}